# Generated by Django 5.2.16 on 2026-08-08 17:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table=None,
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=4)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('prescribed_by', models.CharField(max_length=100)),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile')),
            ],
        ),
    ]
