# Generated by Django 5.2.16 on 2026-08-20 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status_appointmentprescription'),
        ('patients', '0002_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.appointment'),
        ),
    ]
